version: '3.8'

services:

  db:
    image: postgres
    env_file:
     - ./.env

  web:
    build: ../
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env